### ISSUE TITLE
y_testB not defined

### ISSUE THREAD

**Issue by pengyuan-zhou** [rwk506/CrashCatcher#2]
https://github.com/rwk506/CrashCatcher/blob/db422f5135f55e98f515cfec4bf98ef0803b585f/HRNN_training.py#L293

Thx for the fast commit, now that `y_test` works well, yet `y_testB` is not defined now.

**Comment by rwk506** [comment]
Thanks for letting me know -- y_test and y_testB are the same, though. Please change these to one or the other in your code to match accordingly. I will update the commit when I have time, but this code isn't really maintained...
